
#ifndef _PROTOCOL_H
#define _PROTOCOL_H

#define  MAXIMUM_CLIENT_INPUT_BUF_SIZE		256
#define  MAXIMUM_USER_BUFFER_SIZE           10240
#define  MAXIMUM_USER_RECORD_DATA_SIZE			16384
#define  MAXIMUM_HTMLASC_SYNC_DATA_SIZE     10240

#endif